### ISSUE TITLE
lpplmarketwatch.com does not resolve

### ISSUE THREAD

**Issue by chadworth** [bigttrott/thebubbleindex#2]
Simply returns:

>ipfs resolve -r /ipns/QmPC1xcsMTDKFTWHLrGEaNTCEdceUf4wWRJhM5P4kDeUsv/: Could not resolve name.

There are lots of broken links on thebubbleindex.com because of this

**Comment by thebubbleindex** [comment]
Are you still getting the broken links? I host the ipfs server in my local residence so the connection may not be the best.

**Comment by thebubbleindex** [comment]
Closing this since the lpplmarketwatch.com site has move from IPFS to Github pages.
