### ISSUE TITLE
Indicator Value

### ISSUE THREAD

**Issue by ajrmoreira** [bigttrott/thebubbleindex#3]
Hello,

From what I could understand, this allows us to fit the LPPL to the data.
However, which one of the LPPL parameters (A, B, C1, C2, Tc, Omega) is actually used as an indicator?
Or is the indicator the value estimated using the obtained parameters for the LPPL?

Many thanks and great work.

**Comment by thebubbleindex** [comment]
@ajrmoreira I view it the other way around. The idea was to pick out LPPL signals from a timeseries. In other words, the value of The Bubble Index was designed to help show how strongly a given timeseries window show LPPL characteristics.

There are statistical techniques which could be used to estimate all the LPPL parameters, but that is not what this tool does. It assumes we know some of the LPPL parameters (the ones that require complex PhD statistics to estimate) and then attempts to measure in a real time fashion the strength of the LPPL signal. It requires the user to input values for Omega and Tc. The other parameters (A, B, C1, C2) are then estimated after inputting Tc and Omega. It would be awesome if the tool was improved to also estimate Tc and Omega.

The values I use for the public site for Omega and Tc are 2*pi and 21 days respectively.
